<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b4a8cea5-bc59-432e-8632-b70acfa0a6e6</testSuiteGuid>
   <testCaseLink>
      <guid>cb174786-4214-4057-abc9-1ab4d8a46150</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>360d54f7-e7c5-4538-bc07-f0cbeddbc7d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a94c5b-156e-452d-bdc1-a489d87f42d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4b82916-87bb-4bbb-a58b-55b4957722fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a44dd365-6838-45bc-b2ee-4f38bb5738b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC002</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5460e26e-11bd-4b52-a77f-94f48ab5d0e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db8cc3e4-1dad-4a4f-8d97-e9e924164409</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b55582-953c-4085-aace-7be017e3a5d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>007ea9fb-e5f0-4794-9b27-58bda185a88c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC003</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cd928d4-20bb-4199-bc7c-aca408313d3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d497caf5-0fc8-4cb8-858f-250265646e1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf6efa7-b328-4dbe-a260-eef1215717dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2fd0a32-2f2b-461c-8e42-4c777399fd68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC004</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a611e2de-9094-4225-8bb8-754fb1510163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84720b0e-c610-4371-961c-b7c5f03acc3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd578f83-8fb8-410e-9418-8f2ce7cea1ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4543d4e9-8463-42a4-a295-6b916d0f8bf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC005</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46ef5867-c99f-46f3-982c-ba4f61225047</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
